### ISSUE TITLE
Fails with PHP 5.6

### ISSUE THREAD

**Issue by mudrd8mz** [vaughany/moodle-local_ciabinitialsprofilepics#2]
The code uses PHP 7 specific features, whereas Moodle still supports PHP 5.6. As a result, the plugin fails badly:

```
Parse error: syntax error, unexpected ':', expecting '{' in 
/local/ciabinitialsprofilepics/locallib.php on line 60
```

**Comment by mudrd8mz** [comment]
Best would be to follow what Moodle core does and do not rely on PHP 7 specific features. If you insist on using PHP 7, please put a big warning on the plugin description page and perform PHP 7 version check in the plugin code prior to including the files.

**Comment by mudrd8mz** [comment]
I've put a warning on https://moodle.org/plugins/local_ciabinitialsprofilepics but really it would be best to get rid of that dependency.

**Comment by vaughany** [comment]
We're running and coding for PHP 7 for our Moodle installation, but should be able to remove the PHP7-specific elements so that it works in 5.6.
